#!/usr/bin/env python3
"""
swap/check/gate.py — Chapter 8. A Stop hook. The agent says it has finished;
this decides.

Three checks: the contract it claims to produce (the biggest failure bucket),
the exit code of the suite it says it ran, and the bytes of the file it says it
changed. None of the evidence is generated by the model.

    SWAP_WORK=<dir the agent worked in>   SWAP_BASELINE=<untouched fixtures>
    python3 gate.py < event.json

exit 0  the claim holds, let it stop.
exit 2  the claim does not hold. The reason on stderr goes back to the model
        and the run continues. Any OTHER non-zero exit is a non-blocking
        error and the agent stops anyway, which is the trap.
"""
import json, os, pathlib, subprocess, sys

WORK = pathlib.Path(os.environ.get("SWAP_WORK", ".")).resolve()
BASE = pathlib.Path(os.environ["SWAP_BASELINE"]) if os.environ.get("SWAP_BASELINE") else None

ev = json.loads(sys.stdin.read() or "{}")
if ev.get("stop_hook_active"):          # we already pushed back once this turn
    sys.exit(0)

fails = []

# 1. CONTRACT — the output shape it claims to produce. Biggest failure bucket.
r = subprocess.run([sys.executable, "linecount.py", "--json", "sample.txt"],
                   cwd=WORK, capture_output=True, text=True)
if r.returncode != 0:
    fails.append(f"contract: exited {r.returncode}, stderr: {r.stderr.strip()[:160]}")
else:
    try:
        d = json.loads(r.stdout)
        if set(d) != {"file", "lines"}:
            fails.append(f"contract: expected keys file+lines, got {sorted(d)}")
        elif not isinstance(d["lines"], int):
            fails.append(f"contract: lines is {type(d['lines']).__name__}, not int")
    except json.JSONDecodeError as e:
        fails.append(f"contract: stdout is not JSON ({e}); first 80: {r.stdout[:80]!r}")

# 2. EXIT CODE — of the suite it says it ran. Not its summary of the suite.
t = subprocess.run([sys.executable, "-m", "unittest", "discover",
                    "-s", "tests", "-p", "test_*.py"],
                   cwd=WORK, capture_output=True, text=True)
if t.returncode != 0:
    fails.append(f"suite: unittest exited {t.returncode}: {t.stderr.strip()[-200:]}")
if "Ran 0 tests" in (t.stderr + t.stdout):
    fails.append("suite: the runner collected 0 tests — a green run with no tests in it")

# 3. BYTES — did the file it claims to have changed actually change?
if BASE and BASE.exists():
    if (WORK / "linecount.py").read_bytes() == (BASE / "linecount.py").read_bytes():
        fails.append("bytes: linecount.py is byte-identical to the baseline")
    if not (WORK / "tests" / "test_json.py").exists():
        fails.append("bytes: tests/test_json.py does not exist on disk")

if fails:
    print("[swap/check] The run claims to be finished. The evidence disagrees:", file=sys.stderr)
    for f in fails:
        print(f"  - {f}", file=sys.stderr)
    print("Fix these and finish. Do not summarise; the same checks run again.", file=sys.stderr)
    sys.exit(2)

sys.exit(0)
